default_stages: [commit]

repos:
  # ============== PRE-COMMIT HOOKS ===============
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: no-commit-to-branch

  # ==================== PYLINT ====================
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
            "-d duplicate-code",
            "--disable=fixme,import-error,line-too-long",
            "--fail-under=9.5",
            "--good-names=i,j,k,ex,Run,_,pk,x,y,df,e,p",
            "--min-public-methods=0",
          ]
